# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8133d0ce622036e08d96ea2c7073a874088f0c8f29034689bb809fe7afa8ae7461650edfa01c4026135cc2aef19ca72184bb5d514334dffef149338e392fa28
  base_url: https://api-snacks.nerderylabs.com
  api_key: '2bc3457a-bdfd-45f7-8083-5fab09d408f9'

test:
  secret_key_base: 2a42d893a274cadbbd6a7e966007c1fb81cbf2db30f6661e5a18dd71be976e60d7d52e11120e1bfeef944e8aabb01cbf68acff7f51b5aa4afc420781fde62f72
  base_url: https://api-snacks.nerderylabs.com
  api_key: '2bc3457a-bdfd-45f7-8083-5fab09d408f9'
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  base_url: <%= ENV["BASE_URL"] %>
  api_key: <%= ENV["API_KEY"] %>
